
version: "3"
services:
  pymemedb-server:
    container_name: pymemdb-server
    build:
      context: .
    ports:
      - "7000:7000"
    command: poetry run poe run-server
    profiles:
      - pymemedb
      - both
  redis:
    image: redis:latest
    container_name: redis-og-server
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    profiles:
      - redisog
      - both
